// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
      default:
        throw android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdgFRQy6o23SCMqGVhlBH3ITUh9v_epw',
    appId: '1:618315868505:web:9e1720d848b4f794c88448',
    messagingSenderId: '618315868505',
    projectId: 'the-academy-1',
    authDomain: 'the-academy-1.firebaseapp.com',
    storageBucket: 'the-academy-1.appspot.com',
    measurementId: 'G-DWXPHXM37M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBktGlhbRU3tBmWbCukkSfvW0ToPPFISZQ',
    appId: '1:618315868505:android:c3adcc73bb82802cc88448',
    messagingSenderId: '618315868505',
    projectId: 'the-academy-1',
    storageBucket: 'the-academy-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsMsX8urg8QrTOCLd2EJL6lBmkaBwdV_8',
    appId: '1:618315868505:ios:f323b961d4bf6628c88448',
    messagingSenderId: '618315868505',
    projectId: 'the-academy-1',
    storageBucket: 'the-academy-1.appspot.com',
    iosClientId:
        '618315868505-5bv0mnv7e3p6194k7bpk49jcrgq0u2sp.apps.googleusercontent.com',
    iosBundleId: 'com.leenalhamdan.theAcademy',
  );
}
