name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.2.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview
publish_to: none

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.18.0
  #flutter_linkify: ^5.0.2
  url_launcher: ^6.1.7
  #emoji_picker_flutter: ^1.3.0
  http: ^0.13.5
  #html: ^0.15.1
  any_link_preview: ^3.0.0
  #progress_indicators: ^1.0.0
  image_picker: ^0.8.6
  audio_waveforms: ^1.0.1
  #the_academy:
  #  path: ../../the_academy
  voice_message_package: ^1.0.41
  emoji_picker_flutter: ^1.6.1
 # voice_message_package:
 #   path: voice_message_package
 # cached_network_image: ^3.2.1
  

  #audio_wave_url_package: 1.0.31 
  #just_audio: ^0.9.34
  #just_audio_cache: ^0.1.1
  #just_waveform: ^0.0.5
  #shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

